name: Visit FreeNode Page Every Hour

on:
  schedule:
    - cron: '0 * * * *' # 每小时触发一次

jobs:
  visit-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make an HTTP request to the page
      run: |
        curl -s https://getfreenode.pages.dev/
